/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyStorage": {
      "type": "sst.cloudflare.Kv"
    }
    "MyWeb": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "Spotify": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "SpotifyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyRefreshToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
